# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TAVideoPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TAVideoPlayerDemo
  pod 'TACategorys', :git=>'https://tasama@github.com/tasama/TACategorys.git'
  
end
